//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _24jkClient.Client24jk {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Client24jk.IService24")]
    public interface IService24 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService24/UploadPicToDb", ReplyAction="http://tempuri.org/IService24/UploadPicToDbResponse")]
        void UploadPicToDb(string imgUrl, string fName, string fNameExt, int fNameSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService24/UploadPicToDb", ReplyAction="http://tempuri.org/IService24/UploadPicToDbResponse")]
        System.Threading.Tasks.Task UploadPicToDbAsync(string imgUrl, string fName, string fNameExt, int fNameSize);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService24Channel : _24jkClient.Client24jk.IService24, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service24Client : System.ServiceModel.ClientBase<_24jkClient.Client24jk.IService24>, _24jkClient.Client24jk.IService24 {
        
        public Service24Client() {
        }
        
        public Service24Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service24Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service24Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service24Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void UploadPicToDb(string imgUrl, string fName, string fNameExt, int fNameSize) {
            base.Channel.UploadPicToDb(imgUrl, fName, fNameExt, fNameSize);
        }
        
        public System.Threading.Tasks.Task UploadPicToDbAsync(string imgUrl, string fName, string fNameExt, int fNameSize) {
            return base.Channel.UploadPicToDbAsync(imgUrl, fName, fNameExt, fNameSize);
        }
    }
}
